[package]
name = "secsp-syntax-derive"
version = "0.1.0"
authors = ["Gary Tierney <gary.tierney@gmx.com>"]
edition = "2018"
autobenches = false

[dependencies]
syn = "0.15"
quote = "0.6"
proc-macro2="1.0"
Inflector = "0.11"

[lib]
proc-macro = true
bench = false
