[package]
name = "secsp-syntax-derive"
version = "0.1.0"
authors = ["Gary Tierney <gary.tierney@gmx.com>"]
edition = "2018"
autobenches = false

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"
darling = "0.10"

[lib]
proc-macro = true
bench = false
