version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - garyttierney
  ignore:
  - dependency-name: criterion
    versions:
    - ">= 0.3.a, < 0.4"
  - dependency-name: jsonrpc-core
    versions:
    - ">= 13.a, < 14"
  - dependency-name: rowan
    versions:
    - ">= 0.6.a, < 0.7"
  - dependency-name: tokio
    versions:
    - 1.1.0
    - 1.1.1
    - 1.2.0
    - 1.3.0
    - 1.4.0
  - dependency-name: futures
    versions:
    - 0.3.12
    - 0.3.13
  - dependency-name: logos
    versions:
    - 0.11.0
