[package]
name = "secsp_analysis"
version = "0.1.0"
authors = ["Gary Tierney <gary.tierney@gmx.com>"]
edition = "2018"
autobenches = false

[dependencies]
log = "0.4"
rustc-hash = "1.0.1"
salsa = "0.12.1"
secsp_syntax = { path = "../libsecsp_syntax", version = "0.1.0 "}

[lib]
bench = false
