sudo: false
language: rust
# Dependencies of kcov, used by coverage
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

# run builds for all the trains (and more)
rust:
  - beta
  - stable
  - nightly


before_script:
  - |
      cargo install cargo-travis ;
      export PATH=$HOME/.cargo/bin:$PATH

# the main build
script:
  - |
      cargo build --all &&
      cargo test --all &&
      cargo bench --all &&
      cargo doc

after_success:
# measure code coverage and upload to coveralls.io
  - cargo coveralls --all

cache:
  directories:
    - $HOME/.cargo
    - kcov
    - target

env:
  global:
    # override the default `--features unstable` used for the nightly branch (optional)
    - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly
