branches:
  only:
    - staging
    - master
    - trying

sudo: required
language: rust

services:
  - docker

cache: cargo

rust:
  - stable

# the main build
script:
  - |
    cargo build &&
    cargo test
  - |
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      pushd secsp_fuzzer/
      ./tools/run-fuzzer.sh || exit 1
      popd
    else
      echo "Building pull request, not running AFL."
    fi

after_success:
  - docker pull xd009642/tarpaulin:develop-nightly
  - docker run --security-opt seccomp=unconfined -v "$PWD:/volume" xd009642/tarpaulin:develop-nightly sh -c "cargo tarpaulin --out Xml"
  - bash <(curl -s https://codecov.io/bash)
