language: rust
sudo: required
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev
cache: cargo
rust:
  - nightly
script:
- cargo clean --all
- cargo build --all
- cargo test --all
