sudo: required
language: rust

services:
  - docker

cache: cargo

rust:
  - stable

script:
  - docker pull xd009642/tarpaulin:develop-nightly
  - docker run --security-opt seccomp=unconfined -v "$PWD:/volume" xd009642/tarpaulin:develop-nightly sh -c "cargo tarpaulin --out Xml"
  - bash <(curl -s https://codecov.io/bash)
