name: cargo

variables:
  CHANNEL: stable

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: .ci/azure-pipelines-build-and-archive.yml

- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - template: .ci/azure-pipelines-build-and-archive.yml

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: .ci/azure-pipelines-build-and-archive.yml
