name: cargo
pool:
  vmImage:  $[ variables['HOST_IMAGE'] ]
strategy:
  matrix:
    x86_64-pc-windows-gnu:
      HOST_IMAGE: vs2017-win2016
      CHANNEL: stable
    x86_64-pc-windows-msvc:
      HOST_IMAGE: vs2017-win2016
      CHANNEL: stable
    x86_64-apple-darwin:
      HOST_IMAGE: macos-10.13
      CHANNEL: stable
    x86_64-unknown-linux-gnu:
      HOST_IMAGE: ubuntu-16.04
      CHANNEL: stable
steps:
  - powershell: Invoke-WebRequest -Uri https://win.rustup.rs/ -OutFile rustup-init.exe
    condition: and(succeeded(), eq(variables['Agent.OS'],'Windows_NT'))
    displayName: Install rustup [Windows]
  - script: |
      set TARGET=%SYSTEM_JOBDISPLAYNAME%
      rustup-init.exe -y --default-host %TARGET% --default-toolchain %CHANNEL%
      set PATH=%PATH%;%USERPROFILE%\.cargo\bin
      echo "##vso[task.setvariable variable=PATH;]%PATH%"
    condition: and(succeeded(), eq(variables['Agent.OS'],'Windows_NT'))
    displayName: Install toolchain [Windows]
  - script: |
      export TARGET=$SYSTEM_JOBDISPLAYNAME
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-host $TARGET --default-toolchain $CHANNEL
      export PATH=$PATH:~/.cargo/bin
      echo "##vso[task.setvariable variable=PATH;]$PATH"
    condition: and(succeeded(), ne(variables['Agent.OS'],'Windows_NT'))
    displayName: Install rustup and toolchain [Linux & OSX]
  - script: |
      rustc -V
      cargo -V
    displayName: Check rustc and cargo versions
  - script: |
      cargo install cargo2junit
    displayName: Install cargo2junit
  - script: |
      cargo build
    displayName: build
  - script: |
      cargo test --all
    displayName: run tests
  - script: |
      type test_results.json | cargo2junit > test_results_lkg.xml
    condition: and(succeededOrFailed(), eq(variables['Agent.OS'],'Windows_NT'))
    displayName: convert to junit [Windows]
  - script: |
      cat test_results.json | cargo2junit > test_results_lkg.xml
    condition: and(succeededOrFailed(), ne(variables['Agent.OS'],'Windows_NT'))
    displayName: convert to junit [Linux & OSX]
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'test_results_lkg.xml'
      testRunTitle: $(System.JobDisplayName)
      buildPlatform: $(System.JobDisplayName)
    condition: succeededOrFailed()
  - task: CopyFiles@2
    displayName: 'Copy Debug binaries [Windows]'
    inputs:
      Contents: |
        target\debug\secspc.exe
        target\debug\secsp-language-server.exe
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    condition: and(succeeded(), eq(variables['Agent.OS'],'Windows_NT'))
  - task: CopyFiles@2
    displayName: 'Copy Debug binaries [Linux & OSX]'
    inputs:
      Contents: |
        target/debug/secspc
        target/debug/secsp-language-server
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    condition: and(succeeded(), ne(variables['Agent.OS'],'Windows_NT'))
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: secsp-debug-binaries
