name: cargo

variables:
  CHANNEL: stable

jobs:
- job: Linux
  variables:
    target: 'x86_64-unknown-linux-gnu'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: .ci/azure-pipelines-build-and-archive.yml

- job: macOS
  variables:
    target: 'x86_64-apple-darwin'
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - template: .ci/azure-pipelines-build-and-archive.yml

- job: Windows_MSVC
  variables:
    target: 'x86_64-pc-windows-msvc'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: .ci/azure-pipelines-build-and-archive.yml

- job: Windows_GNU
  variables:
    target: 'x86_64-pc-windows-gnu'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: .ci/azure-pipelines-build-and-archive.yml
