[workspace]
members = [
    "packages/libsecsp-analysis",
    "packages/libsecsp-parser",
    "packages/libsecsp-syntax",
    "packages/libsecsp-syntax-derive",
    "packages/secsp-language-server",
    "packages/secspc",
]

[profile.release]
debug = true
panic = 'abort'
