[workspace]
members = [
    "libsecsp_analysis",
    "libsecsp_syntax",
    "secsp_language_server",
    "secspc",
    "tools/sexp_cmp",
]



[profile.release]
debug = true
lto = true
panic = 'abort'
