[workspace]
members = [
    "libsecsp_analysis",
    "libsecsp_syntax",
    "secsp_language_server",
    "secspc",
    "tools/sexp_cmp",
]


[profile.dev]
lto = false

[profile.release]
debug = true
lto = false
panic = 'abort'
