[package]
name = "secsp_syntax"
version = "0.1.0"
authors = ["Gary Tierney <gary.tierney@gmx.com>"]
edition = "2018"

[dependencies]
drop_bomb = "0.1.4"
itertools = "0.8.0"
logos = "0.9.7"
regex = "1.1.0"
rowan = "0.1.3"
smol_str = "0.1.8"
text_unit = "0.1.5"
