cargo-features = ["edition"]

[package]
name = "secsp_syntax"
version = "0.1.0"
authors = ["Gary Tierney <gary.tierney@gmx.com>"]
edition = '2018'

[dependencies]
codespan = "0.1.2"
codespan-reporting = "0.1.3"
pretty_assertions = "0.5.1"
string-interner = "0.6.3"
parking_lot = "0.6.2"
