[package]
name = "secsp-parser"
version = "0.1.0"
authors = ["Gary Tierney <gary.tierney@gmx.com>"]
edition = "2018"
autobenches = false

[dependencies]
bitflags = "1.2"
drop_bomb = "0.1"
itertools = "0.8"
logos = "0.9"
regex = "1.1"
rowan = "0.7"
smol_str = "0.1"
text_unit = "0.1"

[build-dependencies]
ron = "0.5"
quote = "1.0"
serde = "1.0"
Inflector = "0.11"
syn = "1.0"

[lib]
bench = false
