[package]
name = "secsp_syntax"
version = "0.1.0"
authors = ["Gary Tierney <gary.tierney@gmx.com>"]
edition = "2018"
autobenches = false

[dependencies]
itertools = "0.8"
logos = "0.9"
regex = "1.1"
rowan = "0.12"
smol_str = "0.1"
text_unit = "0.1"
secsp-parser = {path="../libsecsp-parser"}
secsp-syntax-derive = {path="../libsecsp-syntax-derive"}

[dev-dependencies]
criterion = "0.3"
criterion_bencher_compat = "0.3"

[[bench]]
name = "parse_file"
path = "benches/parse_file.rs"
harness = false

[lib]
bench = false
