[package]
name = "secsp_language_server"
version = "0.1.0"
authors = ["Gary Tierney <gary.tierney@gmx.com>"]
autobenches = false

[dependencies]
jsonrpc-core = "9.0.0"
lsp-server = "0.2.0"
lsp-types = "0.57.0"
failure = "0.1.5"
crossbeam = "0.7"
crossbeam-channel = "0.3"
crossbeam-utils="0.6"
env_logger = "0.6"
log = "0.4"
secsp_analysis = { path = "../libsecsp-analysis"}
serde=  "1.0"
serde_json = "1.0"
threadpool = "1.7"

[[bin]]
path = "src/main.rs"
name = "secsp-language-server"
bench = false

[lib]
path = "src/lib.rs"
bench = false
