[package]
name = "secsp_syntax"
version = "0.1.0"
authors = ["Gary Tierney <gary.tierney@gmx.com>"]
edition = "2018"
autobenches = false

[dependencies]
drop_bomb = "0.1"
itertools = "0.8"
logos = "0.9"
regex = "1.1"
rowan = "0.2"
smol_str = "0.1"
text_unit = "0.1"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "parse_file"
path = "benches/parse_file.rs"
harness = false

[lib]
bench = false
