[package]
name = "secsp-analysis"
version = "0.1.0"
authors = ["Gary Tierney <gary.tierney@gmx.com>"]
edition = "2018"
autobenches = false

[dependencies]
log = "0.4"
rustc-hash = "1.0"
salsa = "0.13"
secsp-syntax = { path = "../libsecsp-syntax", version = "0.1.0 "}

[lib]
bench = false
