[package]
name = "secspc"
version = "0.1.0"
authors = ["Gary Tierney <gary.tierney@gmx.com>"]
edition = "2018"
autobenches = false

[dependencies]
clap = "2"
fern = "0.6"
log = "0.4"
serde="1.0"
secsp_analysis = { path = "../libsecsp-analysis" }
secsp_syntax = { path = "../libsecsp-syntax" }
symbolic_expressions = "~4.1.9"

[[bin]]
name = "secspc"
path = "src/main.rs"
bench = false
